/**
 * Single source of truth for site identity, navigation, and cross-site links.
 *
 * The Blog (Hugo) and Notes (Quartz) live in separate repos and are
 * served from subdomains of rickgwaterman.com. Dev website deploys should link
 * to the matching dev subdomains so preview traffic stays within dev.
 */

export interface NavLink {
  label: string;
  href: string;
  /** External links open in a new tab and render an arrow indicator. */
  external?: boolean;
}

export interface SocialLink {
  label: string;
  href: string;
}

export interface Project {
  name: string;
  description: string;
  tags?: string[];
  /** Source repository. */
  repo?: string;
  /** Live demo / deployed URL. */
  url?: string;
}

const isDevDeploy = process.env.SITE === 'https://dev.rickgwaterman.com';
const externalLinks = {
  blog: `https://blog${isDevDeploy ? '-dev' : ''}.rickgwaterman.com`,
  notes: `https://docs${isDevDeploy ? '-dev' : ''}.rickgwaterman.com`,
};

export const site = {
  name: 'Rick Waterman',
  role: 'Lead Cloud Architect',
  /** Used for <title>, meta description, and Open Graph tags. */
  description:
    'Rick Waterman — Lead Cloud Architect working in AWS serverless, platform engineering, and data systems.',
  intro:
    'I design and build durable cloud platforms, serverless systems, and data-backed products for teams that need pragmatic architecture and reliable delivery.',
  links: {
    github: 'https://github.com/rwaterman',
    blog: externalLinks.blog,
    notes: externalLinks.notes,
    /** Internal resume page (embeds the compiled Typst PDF). */
    resume: '/resume',
    /** Compiled Typst output, generated by `npm run resume`. */
    resumePdf: '/resume.pdf',
  },
} as const;

export const nav: NavLink[] = [
  { label: 'Bio', href: '/' },
  { label: 'Projects', href: '/projects' },
  { label: 'Resume', href: site.links.resume },
  { label: 'Contact', href: '/contact' },
  { label: 'Links', href: '/links' },
  { label: 'Blog', href: site.links.blog, external: true },
  { label: 'Notes', href: site.links.notes, external: true },
];

export const socials: SocialLink[] = [
  { label: 'GitHub', href: site.links.github },
];

export const projects: Project[] = [
  {
    name: 'Personal Website',
    description:
      'This site — a static Astro hub deployed to S3 + CloudFront via AWS CDK, with a Typst-authored resume.',
    tags: ['Astro', 'AWS', 'CDK', 'TypeScript'],
    repo: 'https://github.com/rwaterman/website',
    url: 'https://rickgwaterman.com',
  },
];
