/**
 * Single source of truth for site identity, navigation, and cross-site links.
 *
 * The Blog (Hugo) and Knowledge Base (Quartz) live in separate repos and are
 * served from subdomains of rickgwaterman.com. Dev website deploys should link
 * to the matching dev subdomains so preview traffic stays within dev.
 */

export interface NavLink {
  label: string;
  href: string;
  /** External links open in a new tab and render an arrow indicator. */
  external?: boolean;
}

export interface Hobby {
  title: string;
  blurb: string;
}

export interface SocialLink {
  label: string;
  href: string;
}

export interface Project {
  name: string;
  description: string;
  tags?: string[];
  /** Source repository. */
  repo?: string;
  /** Live demo / deployed URL. */
  url?: string;
}

const isDevDeploy = process.env.SITE === 'https://dev.rickgwaterman.com';
const externalLinks = {
  blog: `https://blog${isDevDeploy ? '-dev' : ''}.rickgwaterman.com`,
  knowledgeBase: `https://docs${isDevDeploy ? '-dev' : ''}.rickgwaterman.com`,
};

export const site = {
  name: 'Rick Waterman',
  role: 'Lead Cloud Architect',
  /** Used for <title>, meta description, and Open Graph tags. */
  description:
    'Rick Waterman — Lead Cloud Architect working in AWS serverless, platform engineering, and data systems. Synthesizers and graphics shaders on the side.',
  intro:
    'Lead Cloud Architect with 10+ years in backend engineering, AWS serverless, platform engineering, and data systems. Off the clock I make sounds with synthesizers and pixels with graphics shaders.',
  links: {
    github: 'https://github.com/rwaterman',
    blog: externalLinks.blog,
    knowledgeBase: externalLinks.knowledgeBase,
    /** Internal resume page (embeds the compiled Typst PDF). */
    resume: '/resume',
    /** Compiled Typst output, generated by `npm run resume`. */
    resumePdf: '/resume.pdf',
  },
} as const;

export const nav: NavLink[] = [
  { label: 'Bio', href: '/' },
  { label: 'Projects', href: '/projects' },
  { label: 'Memes', href: '/memes' },
  { label: 'Resume', href: site.links.resume },
  { label: 'Contact', href: '/contact' },
  { label: 'Linkfarm', href: '/links' },
  { label: 'Blog', href: site.links.blog, external: true },
  { label: 'Knowledge Base', href: site.links.knowledgeBase, external: true },
];

// Handles are placeholders — update with your real profiles.
export const socials: SocialLink[] = [
  { label: 'GitHub', href: site.links.github },
  { label: 'SoundCloud', href: 'https://soundcloud.com/your-handle' },
  { label: 'Instagram', href: 'https://instagram.com/your-handle' },
  { label: 'X', href: 'https://x.com/your-handle' },
];

// Add your coding projects here — they render on /projects.
export const projects: Project[] = [
  {
    name: 'Personal Website',
    description:
      'This site — a static Astro hub deployed to S3 + CloudFront via AWS CDK, with a Typst-authored resume.',
    tags: ['Astro', 'AWS', 'CDK', 'TypeScript'],
    repo: 'https://github.com/rwaterman/website',
    url: 'https://rickgwaterman.com',
  },
  {
    name: 'Example Project',
    description: 'PLACEHOLDER — replace with one of your projects. Add as many entries as you like.',
    tags: ['TypeScript'],
    repo: 'https://github.com/rwaterman',
  },
];

export const hobbies: Hobby[] = [
  {
    title: 'Music & Synthesizers',
    blurb:
      'Sound design and patch-building on hardware and modular synthesizers — chasing the patch that surprises me.',
  },
  {
    title: 'Graphics & Shaders',
    blurb:
      'Real-time graphics and GLSL/WGSL shaders — generative visuals, raymarching, and the math that makes pixels move.',
  },
];
